### ISSUE TITLE
Using \rm for latex equations remove all font type afterward

### ISSUE THREAD

**Issue by piyueh** [engineersCode/EngComp6_deeplearning#5]
@labarba I noticed you used `\rm` to generate upright fonts for variable names in latex. This does not render fonts properly in notebooks (at least on my machine). If the rendering is not correct on you machine, either, I would suggest using `\mathrm` or `\operatorname` for upright variable names.

For example, the following latex formula
![image](https://user-images.githubusercontent.com/7220966/127376692-42c39d99-4647-4194-91f2-ddf8d4677809.png)
renders
![image](https://user-images.githubusercontent.com/7220966/127376787-08270d46-2db6-4206-bb6c-0ddafc47456d.png)
where the correct rendering should be
![image](https://user-images.githubusercontent.com/7220966/127376870-da75ac98-af73-4707-8823-c9288dd992a0.png)

**Comment by piyueh** [comment]
`\text` should also work fine.

**Comment by labarba** [comment]
Yikes. I didn't notice that. Weird behavior.
